export const vites = [
  {
    id: 1,
    numeral: "N-327-647",
    estado: "óptimo",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "01-06-2023",
    dateAlistamiento: "15-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 2,
    numeral: "N-327-648",
    estado: "crecimiento",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "02-06-2023",
    dateAlistamiento: "16-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 3,
    numeral: "N-327-649",
    estado: "maduro",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "03-06-2023",
    dateAlistamiento: "17-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 4,
    numeral: "N-327-650",
    estado: "plantación",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "04-06-2023",
    dateAlistamiento: "18-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 5,
    numeral: "N-327-651",
    estado: "óptimo",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "05-06-2023",
    dateAlistamiento: "19-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 6,
    numeral: "N-327-652",
    estado: "crecimiento",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "06-06-2023",
    dateAlistamiento: "20-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 7,
    numeral: "N-327-653",
    estado: "maduro",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "07-06-2023",
    dateAlistamiento: "21-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 8,
    numeral: "N-327-654",
    estado: "plantación",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "08-06-2023",
    dateAlistamiento: "22-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 9,
    numeral: "N-327-655",
    estado: "óptimo",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "09-06-2023",
    dateAlistamiento: "23-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 10,
    numeral: "N-327-656",
    estado: "crecimiento",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "10-06-2023",
    dateAlistamiento: "24-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 11,
    numeral: "N-327-657",
    estado: "maduro",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "11-06-2023",
    dateAlistamiento: "25-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 12,
    numeral: "N-327-658",
    estado: "plantación",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "12-06-2023",
    dateAlistamiento: "26-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 13,
    numeral: "N-327-659",
    estado: "óptimo",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "13-06-2023",
    dateAlistamiento: "27-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 14,
    numeral: "N-327-660",
    estado: "crecimiento",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "14-06-2023",
    dateAlistamiento: "28-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 15,
    numeral: "N-327-661",
    estado: "maduro",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "15-06-2023",
    dateAlistamiento: "29-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 16,
    numeral: "N-327-662",
    estado: "plantación",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "16-06-2023",
    dateAlistamiento: "30-06-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 17,
    numeral: "N-327-663",
    estado: "óptimo",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "17-06-2023",
    dateAlistamiento: "01-07-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 18,
    numeral: "N-327-664",
    estado: "crecimiento",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "18-06-2023",
    dateAlistamiento: "02-07-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 19,
    numeral: "N-327-665",
    estado: "maduro",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "19-06-2023",
    dateAlistamiento: "03-07-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
  {
    id: 20,
    numeral: "N-327-666",
    estado: "plantación",
    download: "Descarga el certificado de propiedad",
    lote: "Sembrado en el lote N. 45-C",
    siembra: "20-06-2023",
    dateAlistamiento: "04-07-2023",
    statusAlistamiento: "Vite en alistamiento",
  },
];
